modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszLibrary/issues"

[[mods]]
    modId="majruszlib"
    version="2.11.0-unfinished"
    displayName="Majrusz Library"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszLibrary/1.19/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majrusz-library"
    logoFile="logo.jpg"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Library with common code for some of Majrusz's modifications.'''

[[dependencies.mlib]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
