modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszLibrary/issues"

[[mods]]
    modId="mlib"
    version="3.1.0-unfinished"
    displayName="Majrusz Library"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MinecraftCommon/main/Library/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majrusz-library"
    logoFile="logo.jpg"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Library with common code for my modifications.'''

[[dependencies.mlib]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
