modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszLibrary/issues"

[[mods]]
    modId="mlib"
    version="${versions_mod}"
    displayName="Majrusz Library"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MinecraftCommon/main/Library/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majrusz-library"
    logoFile="logo.jpg"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Library with common code for my modifications.'''

[[dependencies.mlib]]
    modId="forge"
    mandatory=true
    versionRange="${versions_forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mlib]]
    modId="minecraft"
    mandatory=true
    versionRange="${versions_minecraft_range}"
    ordering="NONE"
    side="BOTH"
